esphome:
  name: ledws-example
  platform: ESP8266
  board: esp12e

debug:
logger:
  level: DEBUG

external_components:
  - source: components

# Declare the mainboard
sprocklet:
  id: mainboard


# It is important to set the correct "position" for the children -- it should be in the order they are plugged in 
# so that addressing works correctly
sprocklet_ledws:
  - id: l1
    name: "Test Light 1"
    position: 1
    controller_id: mainboard
    switch_action: none
    num_leds: 8
    # any addressable light properties can follow (effects, etc)                            
    # To expose the switch to Home assistant, set the name property on the switch as shown here, if not set the switch will be private    
    switch:
      name: "Test Light Switch"
      type: momentary
      age: 1000
      # if click_count is configured with a name, a sensor will be present
      # in HA with the current click count
      click_count:
        name: Test Light Switch Click Count
      # if press_duration is configured with a name, a sensor will be present
      # in HA with the current press duration of the switch
      press_duration:
        name: Test Light Switch Press Duration